Repository redhat-developer/gitops-backend, pull requests merged in 2021-03, with the labels that each got.

#15 Update test container go version to 1.15
  openshift-ci/build-root/Dockerfile
Labels: kind/failing-test

#14 Enable unit test run in CI
  Makefile
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/enhancement, lgtm

#18 Update new image registry path
  openshift-ci/build-root/Dockerfile
Labels: kind/failing-ci

#17 Removing unnecessary environment variable
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/cleanup, lgtm, ok-to-test

#16 fix: update default ref from main to HEAD
  pkg/httpapi/api.go
  pkg/httpapi/api_test.go
Labels: approved, lgtm

#19 fix: extract ref from GitOps URL query param
  pkg/httpapi/api.go
  pkg/httpapi/api_test.go
Labels: approved, lgtm
